baseURL = "/"
title = "Ruzica Gajic"
theme = "etch"
languageCode = "en-US"
pygmentsUseClasses = true
pygmentsCodeFences = true
enableInlineShortcodes = true

[params]
  description = "This is my personal blog"
  copyright = "Copyright © 2021 Ruzica Gajic"
  dark = "auto"
  author = "Ruzica Gajic"
  authorURL = "https://www.linkedin.com/in/ruzica-gajic/"
  highlight = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

# [markup]
#   [markup.highlight]
#     anchorLineNos = true
#     codeFences = true
#     guessSyntax = true
#     hl_Lines = ""
#     lineAnchors = ""
#     lineNoStart = 1
#     lineNos = false
#     lineNumbersInTable = true
#     noClasses = true
#     style = "fruity"
#     tabWidth = 4

# [markup.highlight]
#   codeFences = true
#   guessSyntax = true
#   hl_Lines = ""
#   lineNoStart = 0
#   lineNos = true
#   lineNumbersInTable = true
#   tabWidth = 2
#   noClasses = false


[menu]
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "blog"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "resources"
    name = "resources"
    title = "resources"
    url = "/resources/"
    weight = 30

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

[markup.tableOfContents]
  ordered = true
    
